name: Develop Rebase
on:
  push:
    branches:
      # All pushes to this branch will trigger the task.
      - main

jobs:
  rebase_branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Rebase develop on master
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase --autosquash --autostash main develop
          git push --force origin develop
          

